In [1]:
#Data Manipulation specific
import numpy as np
import pandas as pd
import xarray as xr
import netCDF4 as nc
import scipy.stats as stats
from scipy import signal
from netCDF4 import Dataset
#Visualisation specific
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

import cdsapi
import xarray as xr
#import rioxarray
from urllib.request import urlopen# start the client
import requests
import certifi
import urllib3
import cdsapi
from shapely.geometry import mapping
import geopandas as gpd

In [ ]:

r = requests.get("http://google.com")       
print(r.status_code)

In [ ]:

http = urllib3.PoolManager(
    cert_reqs='CERT_REQUIRED',
    ca_certs=certifi.where()
)

In [ ]:
cds = cdsapi.Client()# dataset you want to read

In [ ]:
url = 'https://cds.climate.copernicus.eu/api/v2'
key = '183169:0ba5f9d6-870e-4e73-98a2-120ef76c0683'

## hada dkhal l youtube rah ghatl9a kifach dir had lfichier f  lhome dyalk
with open('C:/Users/ASchynO/.cdsapirc', 'w') as f:
    f.write('\n'.join([url, key]))

with open('C:/Users/ASchynO/.cdsapirc') as f:
    print(f.read())

In [ ]:
c = cdsapi.Client()

c.retrieve(
    'reanalysis-era5-single-levels-monthly-means',
    {
        'format': 'netcdf',
        'product_type': 'monthly_averaged_reanalysis_by_hour_of_day',
        'variable': '2m_temperature',
        'year': [
            '1983', '1984', '1985',
            '1986', '1987', '1988',
            '1989', '1990', '1991',
            '1992', '1993', '1994',
            '1995', '1996', '1997',
            '1998', '1999', '2000',
            '2001', '2002', '2003',
            '2004', '2005', '2006',
            '2007', '2008', '2009',
            '2010', '2011', '2012',
            '2013', '2014', '2015',
            '2016', '2017', '2018',
            '2019', '2020', '2021',
            '2022',
        ],
        'month': [
            '01', '02', '03',
            '04', '05', '06',
            '07', '08', '09',
            '10', '11', '12',
        ],
        'time': [
            '04:00', '05:00', '06:00',
        ],
        'area': [
            37, -18, 20.25,
            0,
        ],
    },
    'download.nc')

In [2]:
tmin = xr.open_dataset('D:\PhD\Datasets\ERA5\min.nc')
tmax = xr.open_dataset('D:\PhD\Datasets\ERA5\max.nc')
p = xr.open_dataset('D:\PhD\Datasets\PERSIANN-CDR\CDR.nc')

c:\Users\ASchynO\anaconda3\lib\site-packages\xarray\backends\plugins.py:65: RuntimeWarning: Engine 'rasterio' loading failed:
DLL load failed while importing _base: The specified module could not be found.
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)

In [90]:
tmax

<xarray.Dataset>
Dimensions:    (longitude: 73, latitude: 68, time: 480)
Coordinates:
  * longitude  (longitude) float32 -18.0 -17.75 -17.5 -17.25 ... -0.5 -0.25 0.0
  * latitude   (latitude) float32 37.0 36.75 36.5 36.25 ... 20.75 20.5 20.25
  * time       (time) datetime64[ns] 1983-01-01T12:00:00 ... 2022-12-01T12:00:00
Data variables:
    t2m        (time, latitude, longitude) float32 15.32 15.3 ... 28.98 28.8
Attributes:
    Conventions:  CF-1.6
    history:      2023-04-03 15:18:57 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [6]:
tmin['t2m'] = (tmin['t2m'] -273.15)
tmax['t2m'] = (tmax['t2m'] -273.15)

In [7]:
p = p.drop_vars('crs')

In [63]:
pdtmin = tmin.to_dataframe(['time', 'latitude', 'longitude'])
pdtmin.columns = ["tmin"]
pdtmax = tmax.to_dataframe(['time', 'latitude', 'longitude'])
pdtmax.columns = ["tmax"]

In [64]:
pdtmin

                                             tmin
time                latitude longitude
1983-01-01 05:00:00 37.00    -18.00     15.053497
                             -17.75     15.043701
                             -17.50     15.028046
                             -17.25     15.028046
                             -17.00     15.041748
...                                           ...
2022-12-01 05:00:00 20.25    -1.00      16.237488
                             -0.75      16.120056
                             -0.50      15.876099
                             -0.25      16.004608
                              0.00      16.037872

[2382720 rows x 1 columns]

In [65]:
import datetime as dt
index = pdtmin.index
index = pdtmin.index.tolist()
newindex = []
for i in index:
    newindex.append((dt.datetime.strftime(i[0], '%Y-%m-%d'), i[1], i[2]))

pdtmin.index = pd.MultiIndex.from_tuples(newindex, names = ['time', 'lat', 'lon'])
pdtmax.index = pd.MultiIndex.from_tuples(newindex, names = ['time', 'lat', 'lon'])

In [66]:
pdtmin

                              tmin
time       lat   lon
1983-01-01 37.00 -18.00  15.053497
                 -17.75  15.043701
                 -17.50  15.028046
                 -17.25  15.028046
                 -17.00  15.041748
...                            ...
2022-12-01 20.25 -1.00   16.237488
                 -0.75   16.120056
                 -0.50   15.876099
                 -0.25   16.004608
                  0.00   16.037872

[2382720 rows x 1 columns]

In [67]:
pdp = p.to_dataframe(['datetime', 'lat', 'lon'])
pdp

                           precip
datetime   lat  lon
1983-01-01 37.5 -17.75  49.714588
                -17.50  46.504448
                -17.25  40.851837
                -17.00  37.140987
                -16.75  41.715736
...                           ...
2022-08-01 20.5 -0.75   38.178108
                -0.50   38.342121
                -0.25   35.542309
                 0.00   43.863758
                 0.25   45.698128

[2397612 rows x 1 columns]

In [68]:
index = pdp.index
index = pdp.index.tolist()
newindex = []
for i in index:
    newindex.append((dt.datetime.strftime(i[0], '%Y-%m-%d'), i[1], i[2]))

pdp.index = pd.MultiIndex.from_tuples(newindex, names = ['time', 'lat', 'lon'])

In [69]:
pdp

                           precip
time       lat  lon
1983-01-01 37.5 -17.75  49.714588
                -17.50  46.504448
                -17.25  40.851837
                -17.00  37.140987
                -16.75  41.715736
...                           ...
2022-08-01 20.5 -0.75   38.178108
                -0.50   38.342121
                -0.25   35.542309
                 0.00   43.863758
                 0.25   45.698128

[2397612 rows x 1 columns]

In [72]:
result = pd.concat([pdp, pdtmin, pdtmax], axis=1, join='inner')

In [73]:
result
#(37.0, 20.5, -17.75, 0) -> (latxlon)=(67x72) (total of 4824 pixel) lat x 67 + lon

                           precip       tmin       tmax
time       lat  lon
1983-01-01 37.0 -17.75  45.372795  15.043701  15.295197
                -17.50  41.519978  15.028046  15.289337
                -17.25  38.298519  15.028046  15.287140
                -17.00  33.130142  15.041748  15.273224
                -16.75  33.649406  15.049591  15.265900
...                           ...        ...        ...
2022-08-01 20.5 -1.00   33.327618  29.673553  39.039154
                -0.75   38.178108  29.646149  39.095551
                -0.50   38.342121  29.685303  39.115356
                -0.25   35.542309  29.497437  38.982025
                 0.00   43.863758  29.034912  38.669922

[2296224 rows x 3 columns]

In [75]:
#print(type(pdp.index.get_level_values("datetime")))
dates = pdp.index.get_level_values("time").to_numpy()
dates = list(dict.fromkeys(dates))
#dates = dates[ : -4]
dates

['1983-01-01',
 '1983-02-01',
 '1983-03-01',
 '1983-04-01',
 '1983-05-01',
 '1983-06-01',
 '1983-07-01',
 '1983-08-01',
 '1983-09-01',
 '1983-10-01',
 '1983-11-01',
 '1983-12-01',
 '1984-01-01',
 '1984-02-01',
 '1984-03-01',
 '1984-04-01',
 '1984-05-01',
 '1984-06-01',
 '1984-07-01',
 '1984-08-01',
 '1984-09-01',
 '1984-10-01',
 '1984-11-01',
 '1984-12-01',
 '1985-01-01',
 '1985-02-01',
 '1985-03-01',
 '1985-04-01',
 '1985-05-01',
 '1985-06-01',
 '1985-07-01',
 '1985-08-01',
 '1985-09-01',
 '1985-10-01',
 '1985-11-01',
 '1985-12-01',
 '1986-01-01',
 '1986-02-01',
 '1986-03-01',
 '1986-04-01',
 '1986-05-01',
 '1986-06-01',
 '1986-07-01',
 '1986-08-01',
 '1986-09-01',
 '1986-10-01',
 '1986-11-01',
 '1986-12-01',
 '1987-01-01',
 '1987-02-01',
 '1987-03-01',
 '1987-04-01',
 '1987-05-01',
 '1987-06-01',
 '1987-07-01',
 '1987-08-01',
 '1987-09-01',
 '1987-10-01',
 '1987-11-01',
 '1987-12-01',
 '1988-01-01',
 '1988-02-01',
 '1988-03-01',
 '1988-04-01',
 '1988-05-01',
 '1988-06-01',
 '1988-07-01',
 '1988-08-01',
 '1988-09-01',
 '1988-10-01',
 '1988-11-01',
 '1988-12-01',
 '1989-01-01',
 '1989-02-01',
 '1989-03-01',
 '1989-04-01',
 '1989-05-01',
 '1989-06-01',
 '1989-07-01',
 '1989-08-01',
 '1989-09-01',
 '1989-10-01',
 '1989-11-01',
 '1989-12-01',
 '1990-01-01',
 '1990-02-01',
 '1990-03-01',
 '1990-04-01',
 '1990-05-01',
 '1990-06-01',
 '1990-07-01',
 '1990-08-01',
 '1990-09-01',
 '1990-10-01',
 '1990-11-01',
 '1990-12-01',
 '1991-01-01',
 '1991-02-01',
 '1991-03-01',
 '1991-04-01',
 '1991-05-01',
 '1991-06-01',
 '1991-07-01',
 '1991-08-01',
 '1991-09-01',
 '1991-10-01',
 '1991-11-01',
 '1991-12-01',
 '1992-01-01',
 '1992-02-01',
 '1992-03-01',
 '1992-04-01',
 '1992-05-01',
 '1992-06-01',
 '1992-07-01',
 '1992-08-01',
 '1992-09-01',
 '1992-10-01',
 '1992-11-01',
 '1992-12-01',
 '1993-01-01',
 '1993-02-01',
 '1993-03-01',
 '1993-04-01',
 '1993-05-01',
 '1993-06-01',
 '1993-07-01',
 '1993-08-01',
 '1993-09-01',
 '1993-10-01',
 '1993-11-01',
 '1993-12-01',
 '1994-01-01',
 '1994-02-01',
 '1994-03-01',
 '1994-04-01',
 '1994-05-01',
 '1994-06-01',
 '1994-07-01',
 '1994-08-01',
 '1994-09-01',
 '1994-10-01',
 '1994-11-01',
 '1994-12-01',
 '1995-01-01',
 '1995-02-01',
 '1995-03-01',
 '1995-04-01',
 '1995-05-01',
 '1995-06-01',
 '1995-07-01',
 '1995-08-01',
 '1995-09-01',
 '1995-10-01',
 '1995-11-01',
 '1995-12-01',
 '1996-01-01',
 '1996-02-01',
 '1996-03-01',
 '1996-04-01',
 '1996-05-01',
 '1996-06-01',
 '1996-07-01',
 '1996-08-01',
 '1996-09-01',
 '1996-10-01',
 '1996-11-01',
 '1996-12-01',
 '1997-01-01',
 '1997-02-01',
 '1997-03-01',
 '1997-04-01',
 '1997-05-01',
 '1997-06-01',
 '1997-07-01',
 '1997-08-01',
 '1997-09-01',
 '1997-10-01',
 '1997-11-01',
 '1997-12-01',
 '1998-01-01',
 '1998-02-01',
 '1998-03-01',
 '1998-04-01',
 '1998-05-01',
 '1998-06-01',
 '1998-07-01',
 '1998-08-01',
 '1998-09-01',
 '1998-10-01',
 '1998-11-01',
 '1998-12-01',
 '1999-01-01',
 '1999-02-01',
 '1999-03-01',
 '1999-04-01',
 '1999-05-01',
 '1999-06-01',
 '1999-07-01',
 '1999-08-01',
 '1999-09-01',
 '1999-10-01',
 '1999-11-01',
 '1999-12-01',
 '2000-01-01',
 '2000-02-01',
 '2000-03-01',
 '2000-04-01',
 '2000-05-01',
 '2000-06-01',
 '2000-07-01',
 '2000-08-01',
 '2000-09-01',
 '2000-10-01',
 '2000-11-01',
 '2000-12-01',
 '2001-01-01',
 '2001-02-01',
 '2001-03-01',
 '2001-04-01',
 '2001-05-01',
 '2001-06-01',
 '2001-07-01',
 '2001-08-01',
 '2001-09-01',
 '2001-10-01',
 '2001-11-01',
 '2001-12-01',
 '2002-01-01',
 '2002-02-01',
 '2002-03-01',
 '2002-04-01',
 '2002-05-01',
 '2002-06-01',
 '2002-07-01',
 '2002-08-01',
 '2002-09-01',
 '2002-10-01',
 '2002-11-01',
 '2002-12-01',
 '2003-01-01',
 '2003-02-01',
 '2003-03-01',
 '2003-04-01',
 '2003-05-01',
 '2003-06-01',
 '2003-07-01',
 '2003-08-01',
 '2003-09-01',
 '2003-10-01',
 '2003-11-01',
 '2003-12-01',
 '2004-01-01',
 '2004-02-01',
 '2004-03-01',
 '2004-04-01',
 '2004-05-01',
 '2004-06-01',
 '2004-07-01',
 '2004-08-01',
 '2004-09-01',
 '2004-10-01',
 '2004-11-01',
 '2004-12-01',
 '2005-01-01',
 '2005-02-01',
 '2005-03-01',
 '2005-04-01',
 '2005-05-01',
 '2005-06-01',
 '2005-07-01',
 '2005-08-01',
 '2005-09-01',
 '2005-10-01',
 '2005-11-01',
 '2005-12-01',
 '2006-01-01',
 '2006-02-01',
 '2006-03-01',
 '2006-04-01',
 '2006-05-01',
 '2006-06-01',
 '2006-07-01',
 '2006-08-01',
 '2006-09-01',
 '2006-10-01',
 '2006-11-01',
 '2006-12-01',
 '2007-01-01',
 '2007-02-01',
 '2007-03-01',
 '2007-04-01',
 '2007-05-01',
 '2007-06-01',
 '2007-07-01',
 '2007-08-01',
 '2007-09-01',
 '2007-10-01',
 '2007-11-01',
 '2007-12-01',
 '2008-01-01',
 '2008-02-01',
 '2008-03-01',
 '2008-04-01',
 '2008-05-01',
 '2008-06-01',
 '2008-07-01',
 '2008-08-01',
 '2008-09-01',
 '2008-10-01',
 '2008-11-01',
 '2008-12-01',
 '2009-01-01',
 '2009-02-01',
 '2009-03-01',
 '2009-04-01',
 '2009-05-01',
 '2009-06-01',
 '2009-07-01',
 '2009-08-01',
 '2009-09-01',
 '2009-10-01',
 '2009-11-01',
 '2009-12-01',
 '2010-01-01',
 '2010-02-01',
 '2010-03-01',
 '2010-04-01',
 '2010-05-01',
 '2010-06-01',
 '2010-07-01',
 '2010-08-01',
 '2010-09-01',
 '2010-10-01',
 '2010-11-01',
 '2010-12-01',
 '2011-01-01',
 '2011-02-01',
 '2011-03-01',
 '2011-04-01',
 '2011-05-01',
 '2011-06-01',
 '2011-07-01',
 '2011-08-01',
 '2011-09-01',
 '2011-10-01',
 '2011-11-01',
 '2011-12-01',
 '2012-01-01',
 '2012-02-01',
 '2012-03-01',
 '2012-04-01',
 '2012-05-01',
 '2012-06-01',
 '2012-07-01',
 '2012-08-01',
 '2012-09-01',
 '2012-10-01',
 '2012-11-01',
 '2012-12-01',
 '2013-01-01',
 '2013-02-01',
 '2013-03-01',
 '2013-04-01',
 '2013-05-01',
 '2013-06-01',
 '2013-07-01',
 '2013-08-01',
 '2013-09-01',
 '2013-10-01',
 '2013-11-01',
 '2013-12-01',
 '2014-01-01',
 '2014-02-01',
 '2014-03-01',
 '2014-04-01',
 '2014-05-01',
 '2014-06-01',
 '2014-07-01',
 '2014-08-01',
 '2014-09-01',
 '2014-10-01',
 '2014-11-01',
 '2014-12-01',
 '2015-01-01',
 '2015-02-01',
 '2015-03-01',
 '2015-04-01',
 '2015-05-01',
 '2015-06-01',
 '2015-07-01',
 '2015-08-01',
 '2015-09-01',
 '2015-10-01',
 '2015-11-01',
 '2015-12-01',
 '2016-01-01',
 '2016-02-01',
 '2016-03-01',
 '2016-04-01',
 '2016-05-01',
 '2016-06-01',
 '2016-07-01',
 '2016-08-01',
 '2016-09-01',
 '2016-10-01',
 '2016-11-01',
 '2016-12-01',
 '2017-01-01',
 '2017-02-01',
 '2017-03-01',
 '2017-04-01',
 '2017-05-01',
 '2017-06-01',
 '2017-07-01',
 '2017-08-01',
 '2017-09-01',
 '2017-10-01',
 '2017-11-01',
 '2017-12-01',
 '2018-01-01',
 '2018-02-01',
 '2018-03-01',
 '2018-04-01',
 '2018-05-01',
 '2018-06-01',
 '2018-07-01',
 '2018-08-01',
 '2018-09-01',
 '2018-10-01',
 '2018-11-01',
 '2018-12-01',
 '2019-01-01',
 '2019-02-01',
 '2019-03-01',
 '2019-04-01',
 '2019-05-01',
 '2019-06-01',
 '2019-07-01',
 '2019-08-01',
 '2019-09-01',
 '2019-10-01',
 '2019-11-01',
 '2019-12-01',
 '2020-01-01',
 '2020-02-01',
 '2020-03-01',
 '2020-04-01',
 '2020-05-01',
 '2020-06-01',
 '2020-07-01',
 '2020-08-01',
 '2020-09-01',
 '2020-10-01',
 '2020-11-01',
 '2020-12-01',
 '2021-01-01',
 '2021-02-01',
 '2021-03-01',
 '2021-04-01',
 '2021-05-01',
 '2021-06-01',
 '2021-07-01',
 '2021-08-01',
 '2021-09-01',
 '2021-10-01',
 '2021-11-01',
 '2021-12-01',
 '2022-01-01',
 '2022-02-01',
 '2022-03-01',
 '2022-04-01',
 '2022-05-01',
 '2022-06-01',
 '2022-07-01',
 '2022-08-01']

In [86]:
lisp = [result.loc[d, 'tmax'].to_numpy() for d in dates]
lisp

C:\Users\ASchynO\AppData\Local\Temp\ipykernel_11480\4153118409.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  lisp = [result.loc[d, 'tmax'].to_numpy() for d in dates]

[array([15.295197, 15.289337, 15.28714 , ..., 20.820557, 20.902618,
        20.652802], dtype=float32),
 array([14.360382, 14.342804, 14.326691, ..., 25.231628, 25.364227,
        25.159088], dtype=float32),
 array([15.021942 , 15.041718 , 15.0607605, ..., 29.882965 , 29.885162 ,
        29.64853  ], dtype=float32),
 array([14.62854 , 14.630737, 14.640259, ..., 36.22812 , 36.212738,
        36.00174 ], dtype=float32),
 array([15.532562, 15.540619, 15.544281, ..., 40.75348 , 40.82599 ,
        40.698517], dtype=float32),
 array([16.865936, 16.867401, 16.902557, ..., 40.79303 , 40.722687,
        40.486786], dtype=float32),
 array([19.118713, 19.12091 , 19.136292, ..., 41.226013, 41.160065,
        40.915375], dtype=float32),
 array([20.077698, 20.03302 , 20.009552, ..., 40.0289  , 39.933685,
        39.67578 ], dtype=float32),
 array([21.00592 , 21.003723, 21.008118, ..., 39.552704, 39.531464,
        39.338074], dtype=float32),
 array([19.961945, 19.98172 , 20.012482, ..., 35.17682 , 35.167297,
        34.924805], dtype=float32),
 array([17.78534 , 17.808807, 17.847626, ..., 30.924011, 31.039032,
        30.828033], dtype=float32),
 array([15.987518, 15.979462, 15.973602, ..., 21.975159, 22.364166,
        22.320953], dtype=float32),
 array([14.865906, 14.887146, 14.908386, ..., 21.391266, 21.541443,
        21.338531], dtype=float32),
 array([13.814606, 13.832184, 13.860016, ..., 24.21109 , 24.31659 ,
        24.08435 ], dtype=float32),
 array([14.354523, 14.362579, 14.38385 , ..., 30.538666, 30.573822,
        30.364288], dtype=float32),
 array([15.650513, 15.654175, 15.665894, ..., 35.7695  , 35.76364 ,
        35.57245 ], dtype=float32),
 array([15.788239, 15.747223, 15.706207, ..., 37.91092 , 37.957825,
        37.792236], dtype=float32),
 array([16.990479, 16.941376, 16.914276, ..., 40.585693, 40.53882 ,
        40.33368 ], dtype=float32),
 array([19.624207, 19.584656, 19.563416, ..., 40.127808, 40.030365,
        39.82892 ], dtype=float32),
 array([20.737793, 20.687225, 20.635956, ..., 40.556396, 40.468475,
        40.23404 ], dtype=float32),
 array([21.104095, 21.05719 , 21.013977, ..., 39.088226, 39.017914,
        38.791534], dtype=float32),
 array([19.888672, 19.882812, 19.874756, ..., 32.595093, 32.716705,
        32.532837], dtype=float32),
 array([17.152374, 17.158234, 17.178009, ..., 28.027985, 28.266083,
        28.207489], dtype=float32),
 array([15.344299, 15.367737, 15.397034, ..., 22.656494, 22.82425 ,
        22.609589], dtype=float32),
 array([14.696655, 14.694458, 14.673218, ..., 21.704102, 21.876251,
        21.755371], dtype=float32),
 array([14.435852, 14.472473, 14.519379, ..., 28.13861 , 28.178192,
        27.939362], dtype=float32),
 array([14.520111, 14.506195, 14.490784, ..., 29.432404, 29.50055 ,
        29.365753], dtype=float32),
 array([14.830719, 14.834381, 14.836578, ..., 33.685974, 33.6669  ,
        33.44565 ], dtype=float32),
 array([15.304718, 15.289337, 15.298859, ..., 36.75415 , 36.806885,
        36.674286], dtype=float32),
 array([17.983887, 17.979492, 17.99121 , ..., 41.72345 , 41.637726,
        41.423065], dtype=float32),
 array([20.164886, 20.164886, 20.168549, ..., 39.253082, 39.206177,
        38.99887 ], dtype=float32),
 array([21.648407, 21.630829, 21.609589, ..., 39.136597, 39.04648 ,
        38.795197], dtype=float32),
 array([21.962708, 21.98175 , 21.989807, ..., 38.6875  , 38.583466,
        38.21277 ], dtype=float32),
 array([20.076233, 20.054993, 20.046936, ..., 34.877197, 34.902832,
        34.71161 ], dtype=float32),
 array([18.262268, 18.299652, 18.33847 , ..., 30.414856, 30.606049,
        30.514496], dtype=float32),
 array([16.605835, 16.605835, 16.619781, ..., 22.010315, 22.153198,
        21.996399], dtype=float32),
 array([15.219757, 15.235138, 15.246857, ..., 21.17807 , 21.38321 ,
        21.209595], dtype=float32),
 array([14.687134, 14.689331, 14.697388, ..., 25.997925, 26.200867,
        26.076324], dtype=float32),
 array([14.083466, 14.06955 , 14.075409, ..., 28.698334, 28.868317,
        28.748901], dtype=float32),
 array([14.025604, 14.011658, 14.003601, ..., 35.728485, 35.837646,
        35.726288], dtype=float32),
 array([16.249786, 16.226349, 16.213165, ..., 39.021576, 39.027435,
        38.84793 ], dtype=float32),
 array([17.238098, 17.243958, 17.257874, ..., 40.878754, 40.962982,
        40.842102], dtype=float32),
 array([19.216156, 19.16925 , 19.138489, ..., 39.70511 , 39.570312,
        39.286774], dtype=float32),
 array([21.435211, 21.391998, 21.361237, ..., 39.982025, 39.880188,
        39.634766], dtype=float32),
 array([20.828613, 20.828613, 20.850586, ..., 37.881622, 37.852325,
        37.647186], dtype=float32),
 array([19.150208, 19.137024, 19.146545, ..., 35.402466, 35.486725,
        35.343872], dtype=float32),
 array([17.665192, 17.63443 , 17.59488 , ..., 26.356903, 26.604523,
        26.548126], dtype=float32),
 array([16.59851 , 16.613892, 16.619781, ..., 21.446228, 21.618378,
        21.44403 ], dtype=float32),
 array([16.253448, 16.255646, 16.249786, ..., 23.560547, 23.870422,
        23.817688], dtype=float32),
 array([15.484955, 15.488617, 15.487152, ..., 26.408936, 26.52835 ,
        26.350311], dtype=float32),
 array([15.694489, 15.715729, 15.729645, ..., 31.014862, 31.091034,
        30.921082], dtype=float32),
 array([15.347229, 15.380188, 15.424866, ..., 35.54019 , 35.52481 ,
        35.274994], dtype=float32),
 array([16.849792, 16.871063, 16.876923, ..., 41.673615, 41.636993,
        41.402557], dtype=float32),
 array([18.90039 , 18.863037, 18.843964, ..., 40.870697, 40.788635,
        40.62674 ], dtype=float32),
 array([20.654266, 20.59784 , 20.554626, ..., 42.223083, 42.148346,
        41.949097], dtype=float32),
 array([21.698242, 21.672577, 21.657196, ..., 40.180573, 40.082397,
        39.84796 ], dtype=float32),
 array([21.630829, 21.644745, 21.65207 , ..., 38.91974 , 38.8963  ,
        38.70874 ], dtype=float32),
 array([18.594147, 18.602203, 18.609528, ..., 36.197357, 36.232513,
        36.02005 ], dtype=float32),
 array([17.286438, 17.288635, 17.288635, ..., 29.95111 , 30.080048,
        29.919617], dtype=float32),
 array([16.648346, 16.609497, 16.583862, ..., 25.580353, 25.771545,
        25.627228], dtype=float32),
 array([15.051239, 15.062958, 15.06662 , ..., 22.104095, 22.27774 ,
        22.158325], dtype=float32),
 array([13.8402405, 13.838043 , 13.848297 , ..., 27.11737  , 27.203796 ,
        27.01773  ], dtype=float32),
 array([14.576508, 14.566986, 14.545013, ..., 30.256592, 30.309357,
        30.125458], dtype=float32),
 array([16.209503, 16.188263, 16.153107, ..., 35.946075, 36.042053,
        35.927032], dtype=float32),
 array([16.936981, 16.915741, 16.890106, ..., 39.319733, 39.33734 ,
        39.1615  ], dtype=float32),
 array([17.793427, 17.765564, 17.738464, ..., 41.740295, 41.72638 ,
        41.564484], dtype=float32),
 array([19.554596, 19.533356, 19.515778, ..., 39.751984, 39.679474,
        39.480194], dtype=float32),
 array([21.339264, 21.286499, 21.23523 , ..., 39.19226 , 39.151245,
        38.936584], dtype=float32),
 array([20.948761, 20.892365, 20.841797, ..., 38.746124, 38.691162,
        38.462585], dtype=float32),
 array([19.227142, 19.230804, 19.230804, ..., 35.873535, 35.855957,
        35.680145], dtype=float32),
 array([17.68573 , 17.68573 , 17.70111 , ..., 28.633148, 28.693207,
        28.499786], dtype=float32),
 array([16.367737, 16.342102, 16.32306 , ..., 20.293823, 20.510681,
        20.358276], dtype=float32),
 array([15.411682 , 15.4036255, 15.388245 , ..., 22.57956  , 22.789093 ,
        22.6521   ], dtype=float32),
 array([15.123779, 15.135498, 15.153076, ..., 25.360565, 25.40744 ,
        25.197906], dtype=float32),
 array([15.114258, 15.09668 , 15.082733, ..., 30.184814, 30.348175,
        30.28006 ], dtype=float32),
 array([14.57431 , 14.570648, 14.566986, ..., 33.93213 , 33.979004,
        33.865448], dtype=float32),
 array([16.802917, 16.820496, 16.851288, ..., 39.41205 , 39.39447 ,
        39.171753], dtype=float32),
 array([19.118713, 19.098938, 19.08133 , ..., 41.534424, 41.474365,
        41.202545], dtype=float32),
 array([21.079163, 21.065979, 21.055725, ..., 39.85309 , 39.836975,
        39.65161 ], dtype=float32),
 array([22.00885 , 21.989075, 21.979553, ..., 38.194458, 38.066986,
        37.79004 ], dtype=float32),
 array([20.751709, 20.689423, 20.632294, ..., 39.92563 , 39.884583,
        39.694855], dtype=float32),
 array([19.476227, 19.491608, 19.5253  , ..., 36.456696, 36.38858 ,
        36.10504 ], dtype=float32),
 array([16.550903, 16.562622, 16.58606 , ..., 30.966492, 30.904236,
        30.622925], dtype=float32),
 array([16.336975, 16.352356, 16.366272, ..., 26.342987, 26.489502,
        26.342987], dtype=float32),
 array([14.549408, 14.530365, 14.520111, ..., 21.172943, 21.432281,
        21.379547], dtype=float32),
 array([14.680542 , 14.666626 , 14.6710205, ..., 26.58255  , 26.780365 ,
        26.698303 ], dtype=float32),
 array([14.764801, 14.769196, 14.799957, ..., 32.151886, 32.136475,
        31.882263], dtype=float32),
 array([14.301788, 14.273956, 14.256348, ..., 34.42224 , 34.508698,
        34.37387 ], dtype=float32),
 array([17.073975, 17.062256, 17.060791, ..., 38.365143, 38.425964,
        38.31021 ], dtype=float32),
 array([18.517975, 18.514313, 18.517975, ..., 41.98059 , 41.967407,
        41.789368], dtype=float32),
 array([20.700409, 20.680634, 20.684296, ..., 39.819397, 39.67874 ,
        39.48532 ], dtype=float32),
 array([22.106293, 22.053558, 22.012512, ..., 40.069214, 39.973236,
        39.758575], dtype=float32),
 array([21.26233 , 21.274048, 21.30188 , ..., 39.803284, 39.67285 ,
        39.411316], dtype=float32),
 array([19.342163, 19.303314, 19.268158, ..., 37.653046, 37.568817,
        37.305054], dtype=float32),
 array([17.71283 , 17.654205, 17.589752, ..., 30.044891, 30.269073,
        30.20459 ], dtype=float32),
 array([15.580933, 15.55307 , 15.539886, ..., 23.518036, 23.738556,
        23.64331 ], dtype=float32),
 array([14.745026, 14.762604, 14.780182, ..., 23.205933, 23.307037,
        23.092407], dtype=float32),
 array([14.272491, 14.251221, 14.235107, ..., 24.309265, 24.60083 ,
        24.6492  ], dtype=float32),
 array([14.55014 , 14.536224, 14.523041, ..., 29.474182, 29.61264 ,
        29.530579], dtype=float32),
 array([14.483459, 14.414612, 14.346466, ..., 34.70575 , 34.776093,
        34.649353], dtype=float32),
 array([15.443207, 15.429993, 15.424133, ..., 35.900635, 35.955597,
        35.812744], dtype=float32),
 array([18.95459 , 18.894531, 18.841766, ..., 40.712433, 40.72415 ,
        40.59375 ], dtype=float32),
 array([20.669647, 20.614685, 20.565613, ..., 39.792267, 39.706573,
        39.53659 ], dtype=float32),
 array([21.74292 , 21.72754 , 21.706299, ..., 39.145386, 38.996674,
        38.74539 ], dtype=float32),
 array([21.79126 , 21.799347, 21.799347, ..., 39.691925, 39.7117  ,
        39.562958], dtype=float32),
 array([18.893066, 18.842499, 18.786102, ..., 35.457428, 35.56732 ,
        35.442017], dtype=float32),
 array([17.83957 , 17.83371 , 17.818329, ..., 29.335724, 29.62436 ,
        29.644135], dtype=float32),
 array([16.697418, 16.6857  , 16.67398 , ..., 24.287292, 24.492401,
        24.306335], dtype=float32),
 array([15.405823, 15.339905, 15.290802, ..., 20.276978, 20.474762,
        20.32605 ], dtype=float32),
 array([14.839508, 14.813873, 14.788239, ..., 28.102722, 28.049988,
        27.729828], dtype=float32),
 array([15.151611, 15.12085 , 15.091553, ..., 26.759125, 26.903442,
        26.855103], dtype=float32),
 array([15.922333 , 15.890808 , 15.8637085, ..., 32.896942 , 32.85959  ,
        32.622955 ], dtype=float32),
 array([16.470306, 16.466644, 16.462982, ..., 37.232544, 37.214966,
        36.97464 ], dtype=float32),
 array([17.769226, 17.745789, 17.716492, ..., 40.845764, 41.00183 ,
        40.939545], dtype=float32),
 array([19.819824, 19.802246, 19.80371 , ..., 40.06189 , 39.963715,
        39.721954], dtype=float32),
 array([21.408844, 21.378082, 21.348785, ..., 39.168823, 39.100708,
        38.873596], dtype=float32),
 array([21.071106, 21.068909, 21.059387, ..., 39.12195 , 39.008392,
        38.739532], dtype=float32),
 array([18.848358, 18.819061, 18.789764, ..., 35.752655, 35.846436,
        35.697723], dtype=float32),
 array([18.109161, 18.064484, 18.031525, ..., 27.792816, 27.880737,
        27.677826], dtype=float32),
 array([16.404388, 16.38095 , 16.370667, ..., 26.24408 , 26.382538,
        26.183289], dtype=float32),
 array([15.961884, 15.936249, 15.910614, ..., 21.043274, 21.080627,
        20.82129 ], dtype=float32),
 array([14.947937, 14.936218, 14.914246, ..., 25.46167 , 25.586212,
        25.433807], dtype=float32),
 array([15.084198 , 15.0607605, 15.0468445, ..., 30.80899  , 30.861755 ,
        30.640503 ], dtype=float32),
 array([15.500336, 15.496674, 15.476898, ..., 35.43396 , 35.457428,
        35.24643 ], dtype=float32),
 array([15.906189, 15.935516, 15.962616, ..., 38.326324, 38.38861 ,
        38.220825], dtype=float32),
 array([18.04544 , 18.043243, 18.039581, ..., 42.33664 , 42.2619  ,
        42.035553], dtype=float32),
 array([19.730438, 19.698944, 19.679169, ..., 40.40988 , 40.313904,
        40.102905], dtype=float32),
 array([20.956085, 20.907013, 20.868195, ..., 39.07724 , 38.96588 ,
        38.764435], dtype=float32),
 array([20.480621, 20.480621, 20.488678, ..., 39.962982, 39.912415,
        39.65454 ], dtype=float32),
 array([18.067413, 18.053497, 18.0513  , ..., 37.51239 , 37.498474,
        37.305054], dtype=float32),
 array([16.178741, 16.141357, 16.106201, ..., 29.27417 , 29.514465,
        29.445618], dtype=float32),
 array([15.372131, 15.372131, 15.372131, ..., 23.196411, 23.249176,
        22.975922], dtype=float32),
 array([14.658569, 14.67395 , 14.689331, ..., 21.015442, 21.123138,
        20.915802], dtype=float32),
 array([14.425598, 14.447571, 14.492249, ..., 26.015503, 26.091705,
        25.894623], dtype=float32),
 array([14.071014, 14.080536, 14.090057, ..., 29.963562, 30.028015,
        29.896881], dtype=float32),
 array([14.731842, 14.714233, 14.689331, ..., 33.86325 , 33.858856,
        33.632477], dtype=float32),
 array([15.9670105, 15.978729 , 15.984589 , ..., 39.375427 , 39.35785  ,
        39.150513 ], dtype=float32),
 array([17.563385, 17.575104, 17.59488 , ..., 41.821625, 41.670685,
        41.34909 ], dtype=float32),
 array([20.263031, 20.241058, 20.222015, ..., 40.58716 , 40.434784,
        40.157135], dtype=float32),
 array([20.911407, 20.911407, 20.918732, ..., 38.854523, 38.66333 ,
        38.31534 ], dtype=float32),
 array([20.822754, 20.805176, 20.793457, ..., 36.686005, 36.637665,
        36.457428], dtype=float32),
 array([20.424225, 20.389069, 20.359741, ..., 34.26767 , 34.291107,
        34.03543 ], dtype=float32),
 array([19.05716 , 19.020538, 18.992706, ..., 29.995056, 30.018494,
        29.779663], dtype=float32),
 array([17.6586  , 17.6315  , 17.597809, ..., 23.47702 , 23.514374,
        23.21695 ], dtype=float32),
 array([16.356018, 16.346497, 16.326721, ..., 20.35608 , 20.448395,
        20.161224], dtype=float32),
 array([15.956024, 15.9758  , 15.993378, ..., 25.489502, 25.489502,
        25.225769], dtype=float32),
 array([15.564087, 15.546478, 15.518646, ..., 29.003113, 29.184784,
        29.087341], dtype=float32),
 array([15.887878, 15.879822, 15.862244, ..., 34.76071 , 34.834686,
        34.707947], dtype=float32),
 array([18.528229, 18.48938 , 18.467407, ..., 39.87213 , 39.848694,
        39.635498], dtype=float32),
 array([18.956055, 18.918701, 18.891602, ..., 41.701477, 41.66629 ,
        41.40329 ], dtype=float32),
 array([20.922394, 20.899689, 20.88797 , ..., 40.846497, 40.831116,
        40.658966], dtype=float32),
 array([22.306305, 22.260864, 22.21399 , ..., 40.272858, 40.12268 ,
        39.907288], dtype=float32),
 array([21.024231, 21.026428, 21.016174, ..., 39.32486 , 39.22525 ,
        38.996674], dtype=float32),
 array([20.024933, 20.036682, 20.050598, ..., 34.919678, 34.95117 ,
        34.72992 ], dtype=float32),
 array([18.079865, 18.108429, 18.149475, ..., 30.436829, 30.44049 ,
        30.163574], dtype=float32),
 array([16.887177, 16.861542, 16.834412, ..., 23.943695, 24.158356,
        24.035278], dtype=float32),
 array([14.55307 , 14.602142, 14.664429, ..., 25.92395 , 25.970825,
        25.699768], dtype=float32),
 array([13.568451, 13.578705, 13.594086, ..., 26.42212 , 26.556915,
        26.391357], dtype=float32),
 array([14.457825, 14.45929 , 14.467346, ..., 30.162842, 30.288116,
        30.077118], dtype=float32),
 array([15.3845825, 15.36554  , 15.351624 , ..., 34.375336 , 34.398804 ,
        34.217102 ], dtype=float32),
 array([15.794128, 15.790436, 15.799988, ..., 39.184937, 39.157837,
        38.932922], dtype=float32),
 array([18.197083, 18.197083, 18.201477, ..., 40.031097, 39.957123,
        39.689728], dtype=float32),
 array([20.156097, 20.103333, 20.065979, ..., 41.24579 , 41.087524,
        40.790833], dtype=float32),
 array([21.781738, 21.77002 , 21.765625, ..., 40.17398 , 40.039185,
        39.78128 ], dtype=float32),
 array([21.179535, 21.128998, 21.076233, ..., 39.67212 , 39.58789 ,
        39.353455], dtype=float32),
 array([20.249115, 20.210297, 20.17514 , ..., 36.362183, 36.39151 ,
        36.145325], dtype=float32),
 array([18.05716 , 18.021973, 17.975098, ..., 28.60382 , 28.713715,
        28.555481], dtype=float32),
 array([15.808777, 15.775787, 15.744293, ..., 25.494629, 25.77594 ,
        25.701233], dtype=float32),
 array([15.2344055, 15.216827 , 15.201416 , ..., 24.024994 , 24.118774 ,
        23.888733 ], dtype=float32),
 array([15.183838, 15.203644, 15.222687, ..., 26.047028, 26.079987,
        25.822113], dtype=float32),
 array([15.50473 , 15.489349, 15.471771, ..., 27.699799, 27.770111,
        27.576721], dtype=float32),
 array([16.744324, 16.744324, 16.746521, ..., 33.02588 , 32.996582,
        32.73282 ], dtype=float32),
 array([16.950897, 16.962616, 16.980225, ..., 38.30435 , 38.308746,
        38.127045], dtype=float32),
 array([18.155334, 18.158997, 18.170715, ..., 41.425262, 41.35495 ,
        41.10074 ], dtype=float32),
 array([19.677704, 19.648376, 19.624939, ..., 41.470703, 41.382782,
        41.179108], dtype=float32),
 array([21.719482, 21.672577, 21.62204 , ..., 39.674316, 39.543915,
        39.293365], dtype=float32),
 array([21.396393, 21.367096, 21.345856, ..., 39.573975, 39.48459 ,
        39.197388], dtype=float32),
 array([20.884308, 20.855011, 20.823486, ..., 35.0325  , 35.12628 ,
        34.991486], dtype=float32),
 array([18.583893, 18.572174, 18.560455, ..., 30.02362 , 30.1958  ,
        30.039032], dtype=float32),
 array([17.194855, 17.132599, 17.076172, ..., 25.097565, 25.296814,
        25.134918], dtype=float32),
 array([15.533295, 15.539154, 15.555267, ..., 23.937836, 24.119507,
        23.947357], dtype=float32),
 array([15.344299, 15.397034, 15.461517, ..., 28.338623, 28.404572,
        28.148895], dtype=float32),
 array([15.68277 , 15.708405, 15.731842, ..., 29.62436 , 29.549622,
        29.237549], dtype=float32),
 array([15.474701, 15.465179, 15.465179, ..., 37.99005 , 38.000305,
        37.783447], dtype=float32),
 array([16.24173 , 16.206573, 16.167755, ..., 38.683105, 38.767365,
        38.63257 ], dtype=float32),
 array([18.798553, 18.79123 , 18.79123 , ..., 41.3161  , 41.247986,
        40.978363], dtype=float32),
 array([20.875519, 20.859406, 20.846191, ..., 41.054565, 40.89853 ,
        40.558594], dtype=float32),
 array([21.625702, 21.569305, 21.5224  , ..., 40.028168, 39.930023,
        39.70584 ], dtype=float32),
 array([22.440369, 22.400818, 22.35611 , ..., 39.44211 , 39.33072 ,
        39.075043], dtype=float32),
 array([20.863068, 20.794922, 20.726776, ..., 35.80835 , 35.918243,
        35.78488 ], dtype=float32),
 array([19.45279 , 19.409546, 19.378052, ..., 28.872711, 28.958405,
        28.715912], dtype=float32),
 array([17.41977 , 17.355316, 17.290833, ..., 23.753937, 24.030884,

In [87]:
stack = np.dstack(lisp)
stack

array([[[15.295197 , 14.360382 , 15.021942 , ..., 18.165588 ,
         19.814697 , 21.220581 ],
        [15.289337 , 14.342804 , 15.041718 , ..., 18.173645 ,
         19.820557 , 21.194916 ],
        [15.28714  , 14.326691 , 15.0607605, ..., 18.191223 ,
         19.841797 , 21.170013 ],
        ...,
        [20.820557 , 25.231628 , 29.882965 , ..., 41.165924 ,
         40.58789  , 39.115356 ],
        [20.902618 , 25.364227 , 29.885162 , ..., 41.015015 ,
         40.48825  , 38.982025 ],
        [20.652802 , 25.159088 , 29.64853  , ..., 40.73001  ,
         40.26187  , 38.66992  ]]], dtype=float32)

In [88]:
def dataframe(p):

    df = pd.DataFrame({'Dates': dates, 'tmax': stack[0][p]})
    df.set_index("Dates", inplace = True)
    return df

In [89]:
dataframe(4823)

                 tmax
Dates
1983-01-01  20.652802
1983-02-01  25.159088
1983-03-01  29.648529
1983-04-01  36.001740
1983-05-01  40.698517
...               ...
2022-04-01  35.050079
2022-05-01  38.644287
2022-06-01  40.730011
2022-07-01  40.261871
2022-08-01  38.669922

[476 rows x 1 columns]

In [91]:
frames = [dataframe(p) for p in range(0, 4824)]

In [ ]:
frames

In [92]:
df = pd.concat(frames,axis=1)

In [93]:
df

,tmax,tmax,tmax,tmax,tmax,tmax,tmax,tmax,tmax,tmax,...,tmax,tmax,tmax,tmax,tmax,tmax,tmax,tmax,tmax,tmax
Dates,,,,,,,,,,,,,,,,,,,,,
1983-01-01,15.295197,15.289337,15.287140,15.273224,15.265900,15.260040,15.263702,15.256378,15.265900,15.262238,...,19.656433,19.738495,19.847656,20.000031,20.394928,20.550964,20.638885,20.820557,20.902618,20.652802
1983-02-01,14.360382,14.342804,14.326691,14.287872,14.239502,14.186768,14.151611,14.134003,14.123749,14.110565,...,23.770050,23.813293,23.922455,24.049927,24.530518,24.813293,24.965668,25.231628,25.364227,25.159088
1983-03-01,15.021942,15.041718,15.060760,15.062958,15.060760,15.049042,15.035858,14.998505,14.943542,14.928162,...,28.934235,29.037537,29.131317,29.209717,29.554749,29.629486,29.736450,29.882965,29.885162,29.648529
1983-04-01,14.628540,14.630737,14.640259,14.638794,14.648315,14.646118,14.644653,14.634399,14.599213,14.572113,...,35.146057,35.302826,35.376831,35.472809,35.836182,35.968781,36.095520,36.228119,36.212738,36.001740
1983-05-01,15.532562,15.540619,15.544281,15.534760,15.519379,15.485687,15.452728,15.417542,15.421204,15.431458,...,39.802551,39.872864,39.891907,39.982025,40.335876,40.441376,40.583496,40.753479,40.825989,40.698517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-04-01,15.591187,15.575806,15.579468,15.593384,15.587524,15.546478,15.503265,15.460785,15.425598,15.390442,...,33.659576,33.763611,33.816376,33.910126,34.331390,34.477905,34.706482,34.952637,35.095520,35.050079
2022-05-01,16.866669,16.874725,16.884247,16.868866,16.884247,16.892303,16.906219,16.936981,16.931122,16.931122,...,37.923401,37.968079,37.976135,38.023010,38.357086,38.460388,38.623016,38.815704,38.833282,38.644287
2022-06-01,18.165588,18.173645,18.191223,18.210266,18.227844,18.224182,18.227844,18.263031,18.309906,18.326019,...,40.677277,40.675812,40.671417,40.735870,40.985718,41.050171,41.146149,41.165924,41.015015,40.730011
2022-07-01,19.814697,19.820557,19.841797,19.841797,19.873291,19.871094,19.865234,19.879150,19.835938,19.824219,...,39.853821,39.896301,39.904358,39.995941,40.285339,40.387177,40.519775,40.587891,40.488251,40.261871
2022-08-01,21.220581,21.194916,21.170013,21.126801,21.115082,21.085754,21.056458,21.017639,20.980286,20.945099,...,38.769562,38.767365,38.773224,38.792999,39.017181,39.039154,39.095551,39.115356,38.982025,38.669922

In [94]:
df.columns = [str(i) for i in range(4824)]
df

,0,1,2,3,4,5,6,7,8,9,...,4814,4815,4816,4817,4818,4819,4820,4821,4822,4823
Dates,,,,,,,,,,,,,,,,,,,,,
1983-01-01,15.295197,15.289337,15.287140,15.273224,15.265900,15.260040,15.263702,15.256378,15.265900,15.262238,...,19.656433,19.738495,19.847656,20.000031,20.394928,20.550964,20.638885,20.820557,20.902618,20.652802
1983-02-01,14.360382,14.342804,14.326691,14.287872,14.239502,14.186768,14.151611,14.134003,14.123749,14.110565,...,23.770050,23.813293,23.922455,24.049927,24.530518,24.813293,24.965668,25.231628,25.364227,25.159088
1983-03-01,15.021942,15.041718,15.060760,15.062958,15.060760,15.049042,15.035858,14.998505,14.943542,14.928162,...,28.934235,29.037537,29.131317,29.209717,29.554749,29.629486,29.736450,29.882965,29.885162,29.648529
1983-04-01,14.628540,14.630737,14.640259,14.638794,14.648315,14.646118,14.644653,14.634399,14.599213,14.572113,...,35.146057,35.302826,35.376831,35.472809,35.836182,35.968781,36.095520,36.228119,36.212738,36.001740
1983-05-01,15.532562,15.540619,15.544281,15.534760,15.519379,15.485687,15.452728,15.417542,15.421204,15.431458,...,39.802551,39.872864,39.891907,39.982025,40.335876,40.441376,40.583496,40.753479,40.825989,40.698517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-04-01,15.591187,15.575806,15.579468,15.593384,15.587524,15.546478,15.503265,15.460785,15.425598,15.390442,...,33.659576,33.763611,33.816376,33.910126,34.331390,34.477905,34.706482,34.952637,35.095520,35.050079
2022-05-01,16.866669,16.874725,16.884247,16.868866,16.884247,16.892303,16.906219,16.936981,16.931122,16.931122,...,37.923401,37.968079,37.976135,38.023010,38.357086,38.460388,38.623016,38.815704,38.833282,38.644287
2022-06-01,18.165588,18.173645,18.191223,18.210266,18.227844,18.224182,18.227844,18.263031,18.309906,18.326019,...,40.677277,40.675812,40.671417,40.735870,40.985718,41.050171,41.146149,41.165924,41.015015,40.730011
2022-07-01,19.814697,19.820557,19.841797,19.841797,19.873291,19.871094,19.865234,19.879150,19.835938,19.824219,...,39.853821,39.896301,39.904358,39.995941,40.285339,40.387177,40.519775,40.587891,40.488251,40.261871
2022-08-01,21.220581,21.194916,21.170013,21.126801,21.115082,21.085754,21.056458,21.017639,20.980286,20.945099,...,38.769562,38.767365,38.773224,38.792999,39.017181,39.039154,39.095551,39.115356,38.982025,38.669922

In [95]:
df.to_csv("tmax_pixels.csv")